version: '3.7'

services:

  app:
    build: .
    container_name: tequila-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    networks:
      - app-network
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: tequila_database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: 'tequila'
      POSTGRES_PASSWORD: 'electrico'
      POSTGRES_DB: 'tequila_electrico'
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
