# Generated by Django 3.2.3 on 2021-06-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210626_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expire_at',
            field=models.DateTimeField(),
        ),
    ]
