# Generated by Django 3.2.3 on 2021-06-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_expire_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='public_price',
        ),
    ]
